import {
  ArrowLeft,
  Box,
  Camera,
  CircleDot,
  ClipboardPaste,
  Copy,
  CopyPlus,
  Cuboid,
  FileBox,
  Folder,
  DoorOpen,
  Image,
  Import,
  Lightbulb,
  List,
  LayoutGrid,
  MapPin,
  MonitorPlay,
  Move3D,
  Package,
  Palette,
  PanelsTopLeft,
  Play,
  Plus,
  Redo2,
  RadioTower,
  Rotate3D,
  Save,
  Scaling,
  Settings2,
  ScreenShare,
  Sparkles,
  Square,
  Trash2,
  Tags,
  TriangleAlert,
  Undo2,
  UploadCloud,
  Globe,
  type LucideIcon,
} from "lucide-react";

export const EDITOR_ICONS = {
  back: ArrowLeft,
  folder: Folder,
  model: Box,
  material: CircleDot,
  texture: Image,
  prefab: Package,
  particle: Sparkles,
  primitive: Cuboid,
  sceneEntity: FileBox,
  light: Lightbulb,
  camera: Camera,
  save: Save,
  upload: UploadCloud,
  play: Play,
  stop: Square,
  copy: Copy,
  paste: ClipboardPaste,
  duplicate: CopyPlus,
  delete: Trash2,
  create: Plus,
  import: Import,
  settings: Settings2,
  asset: Palette,
  undo: Undo2,
  redo: Redo2,
  move: Move3D,
  rotate: Rotate3D,
  scale: Scaling,
  world: Globe,
  item: Box,
  grid: LayoutGrid,
  list: List,
  spawn: MapPin,
  mirror: PanelsTopLeft,
  portal: DoorOpen,
  tagBoard: Tags,
  videoScreen: MonitorPlay,
  liveVideo: RadioTower,
  screenShare: ScreenShare,
  warning: TriangleAlert,
} satisfies Record<string, LucideIcon>;

export type EditorIconName = keyof typeof EDITOR_ICONS;

export function commandTitle(
  label: string,
  _command: string,
  shortcut?: string,
): string {
  return `${label}${shortcut ? ` (${shortcut})` : ""}`;
}
