"""Generate original, seamless PBR maps and UV-mapped catalog sample GLBs.
Run from project root: python tools/catalog-expansion/generate_assets.py
Authoring only: numpy, scipy and Pillow. No downloaded art or runtime dependency.
"""
from pathlib import Path
import sys, json, hashlib, math
import numpy as np
from PIL import Image
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT/'tools/recipe-models'))
from geometry import Model, rot, normalized
from glb import GLB, clean
OUT=ROOT/'public/visual-editor/catalog-samples'
OUT.mkdir(parents=True, exist_ok=True)
N=512
y,x=np.mgrid[0:N,0:N]/N
rng=np.random.default_rng(7351)
# Periodic noise: edges are samples on the same continuous, repeating surface.
noise=sum(np.sin(2*math.pi*(fx*x+fy*y)+rng.uniform(0,6.28))/2**i for i,(fx,fy) in enumerate([(7,9),(19,13),(43,37),(97,61)]))/2
weave=.5+.25*np.sin(2*math.pi*x*80)*np.cos(2*math.pi*y*80)
patterns={
 'carbon':(.45+.28*np.sign(np.sin(2*math.pi*x*16)*np.sin(2*math.pi*y*16))+.16*weave,[22,27,33],[78,88,100],.48,1),
 'fabric':(weave,[44,63,95],[116,142,183],.85,0),
 'leather':(.45+.25*noise+.17*np.sin(2*math.pi*x*31)*np.sin(2*math.pi*y*29),[44,20,13],[130,78,43],.66,0),
 'wood':(.5+.26*np.sin(2*math.pi*x*14+1.6*np.sin(2*math.pi*y*3))+.12*np.sin(2*math.pi*x*70+noise),[56,27,13],[175,119,58],.52,0),
 'marble':(np.clip(1-np.abs(np.sin(2*math.pi*(x*3+y*2)+1.9*noise))*8,0,1),[232,230,217],[64,77,80],.24,0),
 'concrete':(.5+.26*noise,[116,119,121],[186,187,184],.94,0),
 'ceramic':(np.clip(np.minimum(np.sin(2*math.pi*x*4)**2,np.sin(2*math.pi*y*4)**2)*25,0,1),[48,63,69],[187,211,210],.27,0),
 'rust':(.5+.35*noise+.12*np.sin(2*math.pi*(x*13+y*9)),[53,65,69],[183,70,28],.79,1),
 'hammered':(.5+.3*np.cos(2*math.pi*x*24)*np.cos(2*math.pi*y*24),[114,69,35],[216,171,93],.4,1),
 'frosted':(.5+.25*noise,[230,236,240],[253,254,255],.45,0),
 'foil':(.5+.3*np.sin(2*math.pi*(x*12+y*5))+.13*np.cos(2*math.pi*y*32),[75,84,107],[202,216,236],.25,1),
 'brushed':(.5+.22*np.sin(2*math.pi*y*180)+.13*np.sin(2*math.pi*y*47),[123,135,143],[203,213,218],.42,1),
 'brick':(np.minimum(np.sin(2*math.pi*y*5)**2,np.sin(2*math.pi*(x*5+(np.floor(y*10)%2)*.25))**2),[91,67,58],[175,115,84],.88,0),
}
texture_rows=[]
def save_tex(key,role,data,space='linear'):
 fn=f'catalog-{key}-{role}.png';p=OUT/fn
 Image.fromarray(np.uint8(np.clip(data,0,255))).save(p,optimize=True)
 raw=p.read_bytes();sha=hashlib.sha256(raw).hexdigest();tid=f'texture-{p.stem}-{sha[:12]}'
 texture_rows.append(dict(key=f'{key}-{role}',assetId=tid,publicPath=f'/visual-editor/catalog-samples/{fn}',fileName=fn,sha256=sha,byteLength=len(raw),colorSpace=space,displayName=f'{key} / {role}'))
 return tid
textures={}
for key,(height,low,high,rough,metal) in patterns.items():
 h=np.clip(height,0,1);low=np.array(low);high=np.array(high)
 col=low+(high-low)*h[...,None]
 if key=='brick':
  mortar=h<.06;col[mortar]=[172,166,151];h=np.where(mortar,.15,.7+noise*.08)
 if key=='rust':
  rust=h>.5;metal_map=np.where(rust,.08,1);rough_map=np.where(rust,.93,.42)
 else:metal_map=np.full((N,N),metal);rough_map=np.clip(rough+(h-.5)*.16,0,1)
 dx=(np.roll(h,-1,1)-np.roll(h,1,1))*1.8;dy=(np.roll(h,-1,0)-np.roll(h,1,0))*1.8
 normal=np.stack([-dx,dy,np.ones_like(h)],-1);normal/=np.linalg.norm(normal,axis=-1,keepdims=True)
 # R occlusion, G roughness, B metalness as in glTF.
 orm=np.stack([np.clip(.88+.12*h,0,1),rough_map,metal_map],-1)*255
 textures[key]={'color':save_tex(key,'color',col,'srgb'),'normal':save_tex(key,'normal',(normal*.5+.5)*255),'orm':save_tex(key,'orm',orm)}
# Purpose-made emissive masks: dark areas remain dark; bloom is not baked into PNGs.
emasks={
 'circuit':((np.sin(2*math.pi*x*12)**2<.017)&(y%.25<.22))|((np.sin(2*math.pi*y*12)**2<.017)&(x%.25<.19)),
 'grid':(np.minimum(np.sin(2*math.pi*x*8)**2,np.sin(2*math.pi*y*8)**2)<.024),
 'lava':(np.abs(np.sin(2*math.pi*(x*3+y*2)+2.7*noise))<.15),
 'stars':(np.sin(2*math.pi*x*19)**2+np.sin(2*math.pi*y*13)**2<.045),
 'rings':(np.sin(2*math.pi*np.sqrt((x-.5)**2+(y-.5)**2)*8)**2<.035),
 'pixels':((np.floor(x*20)+np.floor(y*12)*7)%11<3)&(x*20%1>.14)&(y*12%1>.14),
}
for key,mask in emasks.items():
 rgb=np.repeat(mask[...,None],3,-1)*255
 textures[key]={'emission':save_tex(key,'emission',rgb,'srgb')}
# Alpha cutout has real transparency, not a black chequer painted onto a panel.
alpha=((np.sin(2*math.pi*x*10)**2<.19)|(np.sin(2*math.pi*y*10)**2<.19))*255
rgba=np.concatenate([np.full((N,N,3),207),alpha[...,None]],-1)
textures['grille']={'color':save_tex('grille','color',rgba,'srgb')}
(ROOT/'tools/catalog-expansion/texture-ids.json').write_text(json.dumps(textures,indent=2))
text='''/** Generated by tools/catalog-expansion/generate_assets.py; project-original PNGs. */
export type CatalogTextureDefinition = {
 key: string; assetId: string; publicPath: string; fileName: string;
 sha256: string; byteLength: number; colorSpace: "srgb" | "linear"; displayName: string;
};
export const CATALOG_TEXTURES: readonly CatalogTextureDefinition[] = '''+json.dumps(texture_rows,ensure_ascii=False,indent=2)+''';
export function getCatalogTexture(assetId: string): CatalogTextureDefinition | undefined {
 return CATALOG_TEXTURES.find((entry) => entry.assetId === assetId);
}
'''
(ROOT/'src/lib/visual-editor/catalog-textures.ts').write_text(text)
# Sample meshes use one named material slot; the catalog assigns editable Material Assets.
models=[]
def emit(key,m):
 parts=[q for p in m.parts if (q:=clean(p)) is not None];g=GLB()
 g.j['asset'].update(generator='XRift Studio catalog samples 1',copyright='Original geometry; MIT')
 g.j['nodes'][0]['name']=key;g.material('Sample Surface',{'color':[.7,.72,.75,1],'roughness':.35,'doubleSided':key=='drape'},OUT)
 g.primitive(parts,0,True,generate_tangents=True)
 fn=f'catalog-{key}.glb';raw=g.write(OUT/fn);sha=hashlib.sha256(raw).hexdigest()
 v=np.vstack([p.vertices for p in parts]);v=v[:,[0,2,1]];v[:,2]*=-1
 models.append(dict(modelId=f'catalog-{key}',assetId=f'model-catalog-{key}-{sha[:12]}',publicPath=f'/visual-editor/catalog-samples/{fn}',fileName=fn,sha256=sha,byteLength=len(raw),displayName=f'質感サンプル / {key}',approxRadius=float(max(np.ptp(v,axis=0))/2),bounds={'min':v.min(0).tolist(),'max':v.max(0).tolist()},provenance='Project-original UV-mapped mesh, reproducible with tools/catalog-expansion/generate_assets.py (MIT).'))
 return
m=Model('shaderball')
profile=[(0,0),(.25,0),(.30,.03)]
for z in np.linspace(.04,.76,49):
 r=math.sqrt(max(0,.39**2-(z-.39)**2))
 # Two physically modeled narrow grooves in the sphere, visible in silhouette.
 r-=.019*math.exp(-((z-.28)/.012)**2)+.013*math.exp(-((z-.61)/.009)**2)
 profile.append((r,z))
profile +=[(.055,.777),(0,.779)]
m.lathe('grooved sample','sample',profile,64);emit('shaderball',m)
m=Model('vase');m.lathe('vessel wall','sample',[(0,0),(.22,0),(.245,.025),(.255,.1),(.29,.22),(.28,.38),(.23,.51),(.16,.61),(.13,.72),(.15,.79),(.15,.82),(.12,.82),(.105,.78),(.10,.72),(.13,.61),(.2,.51),(.25,.37),(.26,.22),(.225,.1),(.215,.05),(0,.05)],64);emit('vase',m)
m=Model('bottle');m.lathe('bottle wall','sample',[(0,0),(.22,0),(.245,.035),(.245,.51),(.23,.56),(.12,.68),(.095,.74),(.095,.95),(.105,.96),(.105,1),(.077,1),(.07,.95),(.07,.73),(.09,.69),(.2,.55),(.22,.50),(.22,.05),(0,.05)],56);emit('bottle',m)
m=Model('drape');vv=[];ff=[];uv=[]
for j in range(49):
 t=j/48
 for i in range(65):
  u=i/64;px=(u-.5)*.92;depth=.12*math.sin(u*math.tau*4)*(1-.27*t)+.13*t*t
  vv.append([px,depth,.90-t*.84+.035*math.cos(u*math.tau*4)*t]);uv.append([u,t])
for j in range(48):
 for i in range(64):
  a=j*65+i;ff.extend([[a,a+65,a+1],[a+1,a+65,a+66]])
m.add('folded fabric','sample',vv,ff,uv);emit('drape',m)
m=Model('gem');m.lathe('faceted crystal','sample',[(0,0),(.09,.05),(.36,.39),(.4,.44),(.4,.47),(.25,.7),(0,.7)],12)
# Preserve genuinely flat-cut facets rather than smoothing the gem into a cone.
for p in m.parts:
 v=p.vertices[p.faces].reshape(-1,3);uv=p.uv[p.faces].reshape(-1,2)
 n=normalized(np.cross(v[1::3]-v[0::3],v[2::3]-v[0::3]))
 p.vertices=v;p.uv=uv;p.faces=np.arange(len(v)).reshape(-1,3);p.normals=np.repeat(n,3,axis=0)
emit('gem',m)
m=Model('tile');m.box('bevelled sample','sample',(0,0,.43),(.88,.07,.86),.025);emit('tile',m)
m=Model('ring');m.torus('ring','sample',.29,.075,center=(0,0,.39),major_seg=72,minor_seg=20,rotation=rot('x',math.pi/2));emit('ring',m)
m=Model('arch');points=[(-.26,0,.08),(-.26,0,.38)]+[(.26*math.cos(a),0,.38+.26*math.sin(a)) for a in np.linspace(math.pi,0,45)]+[(.26,0,.08)]
m.tube('neon arch','sample',points,.027,14);emit('arch',m)
m=Model('knob');m.cylinder('rim','sample',.28,.48,center=(0,0,.28),segments=64,bevel=.018);m.torus('rim top','sample',.259,.018,center=(0,0,.50),major_seg=64,minor_seg=10)
for i in range(48):
 a=i*math.tau/48;m.cylinder(f'knurl {i}','sample',.007,.28,center=(.278*math.cos(a),.278*math.sin(a),.29),segments=6,bevel=0)
emit('knob',m)
m=Model('pedestal');m.cylinder('foot','sample',.37,.04,center=(0,0,.02),segments=64,bevel=.009);m.cylinder('plinth','sample',.34,.095,center=(0,0,.085),segments=64,bevel=.012);emit('pedestal',m)
m=Model('rotor');m.cylinder('hub','sample',.1,.1,segments=32)
for i in range(4):
 a=i*math.pi/2
 p=m.box(f'blade {i}','sample',(.21,0,0),(.39,.13,.05),.019)
 m.transform(p,rotation=rot('z',a))
emit('rotor',m)
m=Model('shutter')
for i in range(8):m.box(f'louver {i}','sample',(0,0,.065+i*.11),(.8,.065,.095),.01)
emit('shutter',m)
text='''import type { BuiltinRecipeModelDefinition } from "./builtin-recipe-models";
/** Reproducible, project-original sample geometry. */
export const CATALOG_SAMPLE_MODELS: readonly BuiltinRecipeModelDefinition[] = '''+json.dumps(models,ensure_ascii=False,indent=2)+';\n'
(ROOT/'src/lib/visual-editor/catalog-sample-models.ts').write_text(text)
(ROOT/'tools/catalog-expansion/asset-report.json').write_text(json.dumps({'models':models,'textures':texture_rows},indent=2,ensure_ascii=False))
print(f'Generated {len(models)} sample GLBs and {len(texture_rows)} PNG maps; {sum(p.stat().st_size for p in OUT.iterdir())/1024/1024:.2f} MiB')
