//! Duplicate, export and import of whole Library projects.
//!
//! A project directory is the unit of exchange. A duplicate is a sibling
//! directory under the same projects root, an export is a zip archive whose
//! single top-level folder is the project directory, and an import unpacks such
//! an archive back into the Library. All three drop the publication record so
//! the resulting project starts as an unpublished, independent project instead
//! of overwriting the original's world when it is published.

use super::*;
use std::io::{Seek, Write};

const PORTABLE_MANIFEST_PATH: &str = ".xrift-studio/package-manifest.json";

/// Hash exactly the bytes written, without buffering a potentially large model.
fn copy_archive_file<R: Read, W: Write>(input: &mut R, output: &mut W) -> std::io::Result<(u64, String)> {
    let mut digest = Sha256::new();
    let mut buffer = [0u8; 64 * 1024];
    let mut size = 0u64;
    loop {
        let count = input.read(&mut buffer)?;
        if count == 0 { break; }
        output.write_all(&buffer[..count])?;
        digest.update(&buffer[..count]);
        size += count as u64;
    }
    Ok((size, format!("{:x}", digest.finalize())))
}

/// Directory names never carried into a copy or an archive, at any depth.
const TRANSFER_SKIPPED_DIRECTORIES: [&str; 1] = [".cache"];

/// Additional directories dropped from a portable archive. They are large,
/// machine-specific, or regenerated by the tooling on the receiving side.
const ARCHIVE_SKIPPED_DIRECTORIES: [&str; 4] = ["node_modules", ".git", "dist", ".xrift-studio-cache"];

/// Files under the project root that record where the project was published.
const PUBLICATION_SIDECARS: [&str; 2] = [".xrift/world.json", ".xrift/item.json"];

const PROJECT_ARCHIVE_MAX_ENTRIES: usize = 200_000;
const PROJECT_ARCHIVE_MAX_UNPACKED_BYTES: u64 = 20 * 1024 * 1024 * 1024;

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ProjectArchiveExport {
    pub archive_path: String,
    pub file_count: u64,
    pub total_bytes: u64,
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ProjectArchiveInspection {
    pub archive_path: String,
    /// Folder name the archive proposes, taken from its top-level folder or the
    /// archive file name.
    pub suggested_name: String,
    pub kind: String,
    pub format: String,
    pub title: Option<String>,
    pub description: Option<String>,
    pub file_count: u64,
    pub total_bytes: u64,
}

/// Resolves a Library project the same way deletion does: a direct child of
/// the root that carries a Visual manifest or `xrift.json`.
fn resolve_library_project(root: &str, project_path: &str) -> Result<PathBuf, String> {
    resolve_deletable_project(root, project_path)
}

fn is_transfer_skipped_directory(name: &str, portable: bool) -> bool {
    TRANSFER_SKIPPED_DIRECTORIES.contains(&name)
        || name.starts_with(".xrift-studio-create-")
        || name.starts_with(RESET_PENDING_PREFIX)
        || (portable && ARCHIVE_SKIPPED_DIRECTORIES.contains(&name))
}

fn is_publication_sidecar(relative: &str) -> bool {
    PUBLICATION_SIDECARS.contains(&relative)
}

/// Walks a project directory and reports every regular file and directory that
/// belongs in a copy. Symlinks are skipped: a copy never follows a link out of
/// the project, and a portable archive never carries one.
fn collect_transfer_entries(
    source: &Path,
    portable: bool,
) -> Result<(Vec<PathBuf>, Vec<PathBuf>), String> {
    let mut directories = Vec::new();
    let mut files = Vec::new();
    let mut pending = vec![PathBuf::new()];
    while let Some(relative) = pending.pop() {
        let absolute = source.join(&relative);
        let entries = std::fs::read_dir(&absolute)
            .map_err(|e| format!("{}: {}", absolute.display(), e))?;
        let mut children: Vec<_> = entries.flatten().collect();
        children.sort_by_key(|entry| entry.file_name());
        for entry in children {
            let name = entry.file_name().to_string_lossy().to_string();
            let child = relative.join(&name);
            let file_type = entry
                .file_type()
                .map_err(|e| format!("{}: {}", entry.path().display(), e))?;
            if file_type.is_symlink() {
                continue;
            }
            if file_type.is_dir() {
                if is_transfer_skipped_directory(&name, portable) {
                    continue;
                }
                directories.push(child.clone());
                pending.push(child);
            } else if file_type.is_file() {
                let unix = child.to_string_lossy().replace('\\', "/");
                if is_publication_sidecar(&unix) {
                    continue;
                }
                files.push(child);
            }
        }
    }
    Ok((directories, files))
}

fn derived_project_id() -> String {
    let digest = Sha256::digest(transaction_id().as_bytes());
    let hex: String = digest.iter().take(16).map(|b| format!("{:02x}", b)).collect();
    format!("project-{}", hex)
}

/// Rewrites the Visual manifest of a freshly copied project so it no longer
/// claims the original's identity or publication.
fn detach_visual_manifest(project_root: &Path, title: Option<&str>) -> Result<(), String> {
    let manifest_path = project_root.join(VISUAL_PROJECT_MANIFEST);
    if !manifest_path.is_file() {
        return Ok(());
    }
    let raw = std::fs::read_to_string(&manifest_path)
        .map_err(|e| format!("visual project manifest cannot be read: {}", e))?;
    let mut value: serde_json::Value = serde_json::from_str(&raw)
        .map_err(|e| format!("invalid visual project manifest: {}", e))?;
    let object = value
        .as_object_mut()
        .ok_or_else(|| "visual project manifest must be an object".to_string())?;
    object.remove("lastPublication");
    object.insert(
        "projectId".to_string(),
        serde_json::Value::String(derived_project_id()),
    );
    if let Some(title) = title {
        if let Some(metadata) = object
            .get_mut("metadata")
            .and_then(|metadata| metadata.as_object_mut())
        {
            metadata.insert(
                "title".to_string(),
                serde_json::Value::String(title.to_string()),
            );
        }
    }
    let content = serde_json::to_string_pretty(&value).map_err(|e| e.to_string())?;
    // The rewritten manifest must still be one Studio can open.
    parse_visual_project_manifest(&content)?;
    write_file_synced(&manifest_path, content.as_bytes())
}

/// Reads a project directory into the Library's `Project` shape.
fn read_library_project_at(path: &Path) -> Result<Project, String> {
    let root = path
        .parent()
        .ok_or_else(|| "project has no parent directory".to_string())?
        .to_string_lossy()
        .to_string();
    let name = path
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| "project directory name is invalid".to_string())?;
    list_projects(root)?
        .into_iter()
        .find(|project| project.name == name)
        .ok_or_else(|| "copied project is not recognized by the Library".to_string())
}

fn copy_project_tree(
    source: &Path,
    destination: &Path,
    portable: bool,
) -> Result<(u64, u64), String> {
    // Directories come from their files' paths, so a directory whose only
    // content was excluded (the publication sidecar) does not come along.
    let (_, files) = collect_transfer_entries(source, portable)?;
    let mut total_bytes = 0u64;
    for file in &files {
        let target = destination.join(file);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        total_bytes += std::fs::copy(source.join(file), &target)
            .map_err(|e| format!("{}: {}", file.display(), e))?;
    }
    Ok((files.len() as u64, total_bytes))
}

/// Creates a temporary sibling under the root, fills it with `build`, and
/// renames it into place. A failure leaves nothing behind.
fn materialize_library_project<F>(
    root: &str,
    directory_name: &str,
    build: F,
) -> Result<Project, String>
where
    F: FnOnce(&Path) -> Result<(), String>,
{
    std::fs::create_dir_all(root).map_err(|e| format!("project root cannot be created: {}", e))?;
    let root_path = PathBuf::from(root)
        .canonicalize()
        .map_err(|e| format!("project root cannot be resolved: {}", e))?;
    let directory_name = validate_project_directory_name(directory_name)?;
    let destination = root_path.join(&directory_name);
    if destination.exists() {
        return Err(format!(
            "同じ名前のプロジェクト「{}」がすでにあります。別の名前を指定してください",
            directory_name
        ));
    }
    let temporary = root_path.join(format!(".xrift-studio-create-{}", transaction_id()));
    if temporary.exists() {
        return Err("temporary project directory already exists".to_string());
    }
    std::fs::create_dir(&temporary).map_err(|e| e.to_string())?;

    let result = (|| {
        build(&temporary)?;
        std::fs::rename(&temporary, &destination)
            .map_err(|e| format!("project cannot be finalized: {}", e))?;
        read_library_project_at(&destination)
    })();

    if result.is_err() && temporary.exists() {
        let _ = force_remove_dir_all(&temporary);
    }
    result
}

#[tauri::command]
pub fn duplicate_project(
    root: String,
    project_path: String,
    directory_name: String,
    title: Option<String>,
) -> Result<Project, String> {
    let _guard = VISUAL_PROJECT_IO_LOCK
        .lock()
        .map_err(|_| "visual project I/O lock is unavailable".to_string())?;
    let source = resolve_library_project(&root, &project_path)?;
    let title = title.map(|value| value.trim().to_string()).filter(|value| !value.is_empty());
    materialize_library_project(&root, &directory_name, |temporary| {
        copy_project_tree(&source, temporary, false)?;
        detach_visual_manifest(temporary, title.as_deref())
    })
}

#[tauri::command]
pub fn export_project_archive(
    root: String,
    project_path: String,
    archive_path: String,
) -> Result<ProjectArchiveExport, String> {
    let _guard = VISUAL_PROJECT_IO_LOCK
        .lock()
        .map_err(|_| "visual project I/O lock is unavailable".to_string())?;
    let source = resolve_library_project(&root, &project_path)?;
    let folder_name = source
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| "project directory name is invalid".to_string())?
        .to_string();
    let archive = PathBuf::from(&archive_path);
    if archive.starts_with(&source) {
        return Err("書き出し先をプロジェクトの中にすることはできません".to_string());
    }
    if let Ok(existing) = std::fs::symlink_metadata(&archive) {
        if !existing.is_file() {
            return Err("書き出し先にはZIPファイルのパスを指定してください".to_string());
        }
    }
    if let Some(parent) = archive.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    // Only files are written: a directory is recreated from its files' paths
    // on import, and a directory left empty by an exclusion never appears.
    let (_, mut files) = collect_transfer_entries(&source, true)?;
    // An imported inventory describes the old archive, not this export.
    files.retain(|path| path != Path::new(PORTABLE_MANIFEST_PATH));
    let file = std::fs::File::create(&archive)
        .map_err(|e| format!("書き出し先に書き込めません: {}", e))?;
    let mut writer = zip::ZipWriter::new(file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .large_file(true);
    let result = (|| {
        writer
            .add_directory(format!("{}/", folder_name), options)
            .map_err(|e| e.to_string())?;
        let mut total_bytes = 0u64;
        let mut portable_files = Vec::with_capacity(files.len());
        for relative in &files {
            let name = format!("{}/{}", folder_name, relative.to_string_lossy().replace('\\', "/"));
            writer.start_file(name, options).map_err(|e| e.to_string())?;
            let mut input = std::fs::File::open(source.join(relative))
                .map_err(|e| format!("{}: {}", relative.display(), e))?;
            let (size, sha256) = copy_archive_file(&mut input, &mut writer)
                .map_err(|e| format!("{}: {}", relative.display(), e))?;
            total_bytes += size;
            portable_files.push(serde_json::json!({
                "path": relative.to_string_lossy().replace('\\', "/"),
                "sha256": sha256,
                "size": size,
            }));
        }
        // This is an archive inventory, not a trust signature or an import gate.
        let manifest = serde_json::json!({
            "format": "xrift-studio-package",
            "formatVersion": 1,
            "studioVersion": env!("CARGO_PKG_VERSION"),
            "files": portable_files,
        });
        let manifest_bytes = serde_json::to_vec_pretty(&manifest).map_err(|e| e.to_string())?;
        writer.start_file(format!("{}/{}", folder_name, PORTABLE_MANIFEST_PATH), options)
            .map_err(|e| e.to_string())?;
        writer.write_all(&manifest_bytes).map_err(|e| e.to_string())?;
        total_bytes += manifest_bytes.len() as u64;
        writer.finish().map_err(|e| e.to_string())?;
        Ok(ProjectArchiveExport {
            archive_path: archive.to_string_lossy().to_string(),
            file_count: files.len() as u64 + 1,
            total_bytes,
        })
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&archive);
    }
    result
}

struct ArchiveLayout {
    /// Entry-name prefix that maps to the project root, `""` or `"folder/"`.
    prefix: String,
    format: String,
}

/// Locates the project root inside an archive: the manifest may sit at the
/// top level or inside exactly one folder. A Visual manifest wins over a
/// Classic `xrift.json` at the same depth, matching the Library's rule.
fn locate_archive_project<R: Read + Seek>(
    archive: &mut zip::ZipArchive<R>,
) -> Result<ArchiveLayout, String> {
    let mut best: Option<(usize, String, String)> = None;
    for index in 0..archive.len() {
        let entry = archive.by_index(index).map_err(|e| e.to_string())?;
        if entry.is_dir() {
            continue;
        }
        let Some(path) = entry.enclosed_name() else {
            return Err("アーカイブに安全でないパスが含まれています".to_string());
        };
        let components: Vec<String> = path
            .components()
            .map(|c| c.as_os_str().to_string_lossy().to_string())
            .collect();
        let Some(file_name) = components.last() else { continue };
        let format = if file_name == VISUAL_PROJECT_MANIFEST {
            "visual"
        } else if file_name == "xrift.json" {
            "classic"
        } else {
            continue;
        };
        let depth = components.len() - 1;
        if depth > 1 {
            continue;
        }
        let prefix = components[..depth]
            .iter()
            .map(|c| format!("{}/", c))
            .collect::<String>();
        let rank = depth * 2 + if format == "visual" { 0 } else { 1 };
        if best.as_ref().map(|(r, _, _)| rank < *r).unwrap_or(true) {
            best = Some((rank, prefix, format.to_string()));
        }
    }
    let (_, prefix, format) = best.ok_or_else(|| {
        format!(
            "アーカイブの直下または1つのフォルダーの中に {} か xrift.json が見つかりません",
            VISUAL_PROJECT_MANIFEST
        )
    })?;
    Ok(ArchiveLayout { prefix, format })
}

fn suggested_name_for_archive(archive_path: &Path, prefix: &str) -> String {
    let folder = prefix.trim_end_matches('/');
    let candidate = if folder.is_empty() {
        archive_path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or("imported-project")
            .to_string()
    } else {
        folder.to_string()
    };
    let cleaned: String = candidate
        .trim()
        .chars()
        .map(|c| if matches!(c, '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|') { '-' } else { c })
        .collect();
    let cleaned = cleaned.trim_matches(|c| c == '.' || c == ' ' || c == '-');
    if cleaned.is_empty() || cleaned == ".cache" || cleaned.starts_with(".xrift-studio-create-") {
        "imported-project".to_string()
    } else {
        cleaned.to_string()
    }
}

fn open_project_archive(archive_path: &str) -> Result<(PathBuf, zip::ZipArchive<std::fs::File>), String> {
    let path = PathBuf::from(archive_path);
    let metadata = std::fs::symlink_metadata(&path)
        .map_err(|e| format!("アーカイブを開けません: {}", e))?;
    if !metadata.is_file() {
        return Err("アーカイブは通常のファイルである必要があります".to_string());
    }
    let file = std::fs::File::open(&path).map_err(|e| format!("アーカイブを開けません: {}", e))?;
    let archive = zip::ZipArchive::new(file)
        .map_err(|e| format!("ZIPアーカイブとして読み込めません: {}", e))?;
    if archive.len() > PROJECT_ARCHIVE_MAX_ENTRIES {
        return Err("ZIP内のファイル・フォルダー数が多すぎます".to_string());
    }
    Ok((path, archive))
}

/// Relative path of an archive entry inside the project, or `None` when the
/// entry sits outside the project folder or is excluded from a transfer.
fn archive_entry_relative_path(
    entry: &zip::read::ZipFile<'_>,
    prefix: &str,
) -> Result<Option<PathBuf>, String> {
    let Some(enclosed) = entry.enclosed_name() else {
        return Err("アーカイブに安全でないパスが含まれています".to_string());
    };
    let unix = enclosed.to_string_lossy().replace('\\', "/");
    let Some(rest) = unix.strip_prefix(prefix) else {
        return Ok(None);
    };
    let rest = rest.trim_end_matches('/');
    if rest.is_empty() {
        return Ok(None);
    }
    let relative = validate_relative_path(rest, false)?;
    let mut has_skipped = false;
    for (index, component) in relative.components().enumerate() {
        let name = component.as_os_str().to_string_lossy();
        let is_last = index + 1 == relative.components().count();
        if (!is_last || entry.is_dir()) && is_transfer_skipped_directory(&name, true) {
            has_skipped = true;
            break;
        }
    }
    if has_skipped || is_publication_sidecar(rest) {
        return Ok(None);
    }
    Ok(Some(relative))
}

#[tauri::command]
pub fn inspect_project_archive(archive_path: String) -> Result<ProjectArchiveInspection, String> {
    let (path, mut archive) = open_project_archive(&archive_path)?;
    let layout = locate_archive_project(&mut archive)?;

    let manifest_name = if layout.format == "visual" { VISUAL_PROJECT_MANIFEST } else { "xrift.json" };
    let mut manifest_raw = String::new();
    archive
        .by_name(&format!("{}{}", layout.prefix, manifest_name))
        .map_err(|e| e.to_string())?
        .read_to_string(&mut manifest_raw)
        .map_err(|e| e.to_string())?;

    let (kind, title, description) = if layout.format == "visual" {
        let manifest = parse_visual_project_manifest(&manifest_raw)?;
        let description = manifest.metadata.description.trim().to_string();
        (
            manifest.project_kind,
            Some(manifest.metadata.title),
            if description.is_empty() { None } else { Some(description) },
        )
    } else {
        let parsed: XriftJson = serde_json::from_str(&manifest_raw)
            .map_err(|e| format!("xrift.json を読み込めません: {}", e))?;
        if let Some(item) = parsed.item {
            ("item".to_string(), item.title, item.description)
        } else if let Some(world) = parsed.world {
            ("world".to_string(), world.title, world.description)
        } else {
            ("world".to_string(), parsed.title, parsed.description)
        }
    };

    let mut file_count = 0u64;
    let mut total_bytes = 0u64;
    for index in 0..archive.len() {
        let entry = archive.by_index(index).map_err(|e| e.to_string())?;
        if entry.is_dir() {
            continue;
        }
        if archive_entry_relative_path(&entry, &layout.prefix)?.is_some() {
            file_count += 1;
            total_bytes = total_bytes.saturating_add(entry.size());
        }
    }
    if total_bytes > PROJECT_ARCHIVE_MAX_UNPACKED_BYTES {
        return Err("アーカイブの展開後サイズが大きすぎます".to_string());
    }

    Ok(ProjectArchiveInspection {
        archive_path: path.to_string_lossy().to_string(),
        suggested_name: suggested_name_for_archive(&path, &layout.prefix),
        kind,
        format: layout.format,
        title,
        description,
        file_count,
        total_bytes,
    })
}

#[tauri::command]
pub fn import_project_archive(
    root: String,
    archive_path: String,
    directory_name: String,
) -> Result<Project, String> {
    let _guard = VISUAL_PROJECT_IO_LOCK
        .lock()
        .map_err(|_| "visual project I/O lock is unavailable".to_string())?;
    // Inspection validates the layout, the manifest and the unpacked size
    // before a single byte lands under the root.
    inspect_project_archive(archive_path.clone())?;
    let (_, mut archive) = open_project_archive(&archive_path)?;
    let layout = locate_archive_project(&mut archive)?;

    materialize_library_project(&root, &directory_name, |temporary| {
        let mut unpacked = 0u64;
        for index in 0..archive.len() {
            let mut entry = archive.by_index(index).map_err(|e| e.to_string())?;
            let Some(relative) = archive_entry_relative_path(&entry, &layout.prefix)? else {
                continue;
            };
            if entry.is_dir() {
                continue;
            }
            let target = temporary.join(&relative);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            let mut output = std::fs::File::create(&target)
                .map_err(|e| format!("{}: {}", relative.display(), e))?;
            unpacked = unpacked.saturating_add(
                std::io::copy(&mut entry, &mut output)
                    .map_err(|e| format!("{}: {}", relative.display(), e))?,
            );
            if unpacked > PROJECT_ARCHIVE_MAX_UNPACKED_BYTES {
                return Err("アーカイブの展開後サイズが大きすぎます".to_string());
            }
            output.flush().map_err(|e| e.to_string())?;
        }
        if !temporary.join(VISUAL_PROJECT_MANIFEST).is_file() && !temporary.join("xrift.json").is_file()
        {
            return Err("アーカイブからプロジェクトの定義を取り出せませんでした".to_string());
        }
        detach_visual_manifest(temporary, None)
    })
}

/// Clones a Git repository and takes it into the Library as a new, unpublished
/// project. The clone is a shallow, single-branch checkout; `.git` is not kept,
/// because the result is a fork of the content, not of the history.
#[tauri::command]
pub async fn import_project_from_repository(
    root: String,
    repository_url: String,
    directory_name: String,
) -> Result<Project, String> {
    let repository_url = validate_classic_repository_url(&repository_url)?;
    // Validate the destination before the network round trip.
    validate_project_directory_name(&directory_name)?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|error| error.to_string())?
        .as_nanos();
    let clone_root = std::env::temp_dir()
        .join("xrift-studio")
        .join("repository-import")
        .join(format!("{}-{}", std::process::id(), nonce));
    let parent = clone_root
        .parent()
        .ok_or_else(|| "repository cache path is invalid".to_string())?;
    std::fs::create_dir_all(parent).map_err(|error| error.to_string())?;

    let output = tokio::process::Command::new("git")
        .args(["clone", "--depth", "1", "--single-branch", "--no-tags", "--", &repository_url])
        .arg(&clone_root)
        .env("GIT_TERMINAL_PROMPT", "0")
        .output()
        .await
        .map_err(|error| format!("gitを起動できませんでした: {}", error))?;
    if !output.status.success() {
        let _ = force_remove_dir_all(&clone_root);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let message = stderr.lines().last().unwrap_or("git clone failed").trim();
        return Err(format!("リポジトリを取得できませんでした: {}", message));
    }

    let result = take_checkout_into_library(&root, &clone_root, &directory_name);
    let _ = force_remove_dir_all(&clone_root);
    result
}

/// Copies a finished checkout into the Library as a new project, dropping
/// `.git`, caches and the publication record on the way.
fn take_checkout_into_library(
    root: &str,
    checkout: &Path,
    directory_name: &str,
) -> Result<Project, String> {
    inspect_cloned_repository_tree(checkout)?;
    if !checkout.join(VISUAL_PROJECT_MANIFEST).is_file() && !checkout.join("xrift.json").is_file() {
        return Err(format!(
            "リポジトリの直下に {} か xrift.json がありません",
            VISUAL_PROJECT_MANIFEST
        ));
    }
    let _guard = VISUAL_PROJECT_IO_LOCK
        .lock()
        .map_err(|_| "visual project I/O lock is unavailable".to_string())?;
    materialize_library_project(root, directory_name, |temporary| {
        copy_project_tree(checkout, temporary, true)?;
        detach_visual_manifest(temporary, None)
    })
}

/// Size and entry-type limits shared with the Classic repository import, minus
/// its Classic-only manifest check.
fn inspect_cloned_repository_tree(repository_root: &Path) -> Result<(), String> {
    const MAX_REPOSITORY_FILES: usize = 20_000;
    const MAX_REPOSITORY_BYTES: u64 = 768 * 1024 * 1024;
    let mut pending = vec![repository_root.to_path_buf()];
    let mut file_count = 0usize;
    let mut total_bytes = 0u64;
    while let Some(directory) = pending.pop() {
        for entry in std::fs::read_dir(&directory).map_err(|error| error.to_string())? {
            let entry = entry.map_err(|error| error.to_string())?;
            if entry.file_name().to_string_lossy().eq_ignore_ascii_case(".git") {
                continue;
            }
            let metadata =
                std::fs::symlink_metadata(entry.path()).map_err(|error| error.to_string())?;
            if metadata.file_type().is_symlink() {
                return Err("repository contains a symbolic link".to_string());
            }
            if metadata.is_dir() {
                pending.push(entry.path());
                continue;
            }
            if !metadata.is_file() {
                return Err("repository contains an unsupported filesystem entry".to_string());
            }
            file_count = file_count.saturating_add(1);
            total_bytes = total_bytes.saturating_add(metadata.len());
            if file_count > MAX_REPOSITORY_FILES || total_bytes > MAX_REPOSITORY_BYTES {
                return Err("repository is too large to import safely".to_string());
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(path: &Path, content: &str) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, content).unwrap();
    }

    fn visual_manifest(project_id: &str, published: bool) -> String {
        let publication = if published {
            r#","lastPublication":{"uploadedAt":"2026-01-01T00:00:00Z","worldId":"w1"}"#
        } else {
            ""
        };
        format!(
            r#"{{"schemaVersion":"{}","projectId":"{}","projectKind":"world","metadata":{{"name":"demo","title":"Demo","description":""}},"entrySceneId":"scene-1","scenePaths":{{"scene-1":"scenes/main.json"}},"assetManifestPath":"assets.json"{}}}"#,
            VISUAL_PROJECT_SCHEMA_VERSION, project_id, publication
        )
    }

    fn temp_root(label: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "xrift-transfer-{}-{}",
            label,
            transaction_id()
        ));
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    fn seed_visual_project(root: &Path, name: &str) -> PathBuf {
        let project = root.join(name);
        write(&project.join(VISUAL_PROJECT_MANIFEST), &visual_manifest("project-original", true));
        write(&project.join("scenes/main.json"), "{}");
        write(&project.join("assets.json"), "{}");
        write(&project.join("node_modules/pkg/index.js"), "x");
        write(&project.join(".cache/tmp"), "x");
        write(&project.join(".xrift/world.json"), "{}");
        project
    }

    #[test]
    fn duplicate_copies_files_and_detaches_publication() {
        let root = temp_root("dup");
        let source = seed_visual_project(&root, "demo");
        let copy = duplicate_project(
            root.to_string_lossy().to_string(),
            source.to_string_lossy().to_string(),
            "demo-copy".to_string(),
            Some("Demo Copy".to_string()),
        )
        .unwrap();
        assert_eq!(copy.name, "demo-copy");
        assert_eq!(copy.title.as_deref(), Some("Demo Copy"));
        assert!(copy.uploaded_at.is_none());
        let dest = root.join("demo-copy");
        assert!(dest.join("scenes/main.json").is_file());
        assert!(dest.join("node_modules/pkg/index.js").is_file());
        assert!(!dest.join(".cache").exists());
        assert!(!dest.join(".xrift/world.json").exists());
        let manifest = std::fs::read_to_string(dest.join(VISUAL_PROJECT_MANIFEST)).unwrap();
        assert!(!manifest.contains("project-original"));
        assert!(!manifest.contains("lastPublication"));
        assert!(
            duplicate_project(
                root.to_string_lossy().to_string(),
                source.to_string_lossy().to_string(),
                "demo-copy".to_string(),
                None,
            )
            .is_err()
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn export_then_import_round_trips_without_node_modules() {
        let root = temp_root("archive");
        let source = seed_visual_project(&root, "demo");
        let archive = root.join("out").join("demo.zip");
        let exported = export_project_archive(
            root.to_string_lossy().to_string(),
            source.to_string_lossy().to_string(),
            archive.to_string_lossy().to_string(),
        )
        .unwrap();
        assert_eq!(exported.file_count, 4);

        let inspection = inspect_project_archive(archive.to_string_lossy().to_string()).unwrap();
        assert_eq!(inspection.suggested_name, "demo");
        assert_eq!(inspection.format, "visual");
        assert_eq!(inspection.kind, "world");
        assert_eq!(inspection.title.as_deref(), Some("Demo"));

        let imported = import_project_archive(
            root.to_string_lossy().to_string(),
            archive.to_string_lossy().to_string(),
            "demo-imported".to_string(),
        )
        .unwrap();
        assert_eq!(imported.format, "visual");
        assert!(imported.uploaded_at.is_none());
        let dest = root.join("demo-imported");
        assert!(dest.join("scenes/main.json").is_file());
        assert!(!dest.join("node_modules").exists());
        assert!(!dest.join(".xrift").exists());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn archive_inventory_hashes_written_bytes_and_replaces_old_inventory() {
        let root = temp_root("inventory");
        let source = seed_visual_project(&root, "demo");
        write(&source.join(PORTABLE_MANIFEST_PATH), "stale inventory");
        let payload = vec![42u8; 150_000];
        std::fs::write(source.join("large.glb"), &payload).unwrap();
        let archive_path = root.join("out/demo.zip");
        let exported = export_project_archive(
            root.to_string_lossy().to_string(), source.to_string_lossy().to_string(),
            archive_path.to_string_lossy().to_string(),
        ).unwrap();
        let mut archive = zip::ZipArchive::new(std::fs::File::open(&archive_path).unwrap()).unwrap();
        let name = format!("demo/{}", PORTABLE_MANIFEST_PATH);
        assert_eq!(archive.file_names().filter(|entry| *entry == name).count(), 1);
        let manifest: serde_json::Value = serde_json::from_reader(archive.by_name(&name).unwrap()).unwrap();
        assert_eq!(manifest["formatVersion"], 1);
        let entries = manifest["files"].as_array().unwrap();
        assert_eq!(entries.len(), 4);
        assert_eq!(exported.file_count, 5);
        let mut total = archive.by_name(&name).unwrap().size();
        for entry in entries {
            let path = entry["path"].as_str().unwrap();
            assert_ne!(path, PORTABLE_MANIFEST_PATH);
            let mut bytes = Vec::new();
            archive.by_name(&format!("demo/{}", path)).unwrap().read_to_end(&mut bytes).unwrap();
            assert_eq!(entry["size"].as_u64().unwrap(), bytes.len() as u64);
            assert_eq!(entry["sha256"].as_str().unwrap(), format!("{:x}", Sha256::digest(&bytes)));
            total += bytes.len() as u64;
        }
        assert_eq!(exported.total_bytes, total);
        drop(archive);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn checkout_is_taken_in_without_git_or_publication() {
        let root = temp_root("checkout");
        let checkout = seed_visual_project(&root, "checkout");
        write(&checkout.join(".git/HEAD"), "ref: refs/heads/main");
        let imported = take_checkout_into_library(
            &root.to_string_lossy(),
            &checkout,
            "forked-world",
        )
        .unwrap();
        assert_eq!(imported.name, "forked-world");
        assert!(imported.uploaded_at.is_none());
        let dest = root.join("forked-world");
        assert!(dest.join("scenes/main.json").is_file());
        assert!(!dest.join(".git").exists());
        assert!(!dest.join("node_modules").exists());
        assert!(!dest.join(".xrift").exists());

        let empty = root.join("empty");
        std::fs::create_dir_all(&empty).unwrap();
        assert!(take_checkout_into_library(&root.to_string_lossy(), &empty, "nothing").is_err());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn import_rejects_archives_without_a_project() {
        let root = temp_root("bad");
        let archive = root.join("bad.zip");
        let file = std::fs::File::create(&archive).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        writer
            .start_file("notes.txt", zip::write::SimpleFileOptions::default())
            .unwrap();
        writer.write_all(b"hi").unwrap();
        writer.finish().unwrap();
        assert!(inspect_project_archive(archive.to_string_lossy().to_string()).is_err());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn import_accepts_classic_archive_at_top_level() {
        let root = temp_root("classic");
        let archive = root.join("classic.zip");
        let file = std::fs::File::create(&archive).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        let options = zip::write::SimpleFileOptions::default();
        writer.start_file("xrift.json", options).unwrap();
        writer
            .write_all(br#"{"world":{"title":"Classic","description":"d"}}"#)
            .unwrap();
        writer.start_file("package.json", options).unwrap();
        writer.write_all(b"{}").unwrap();
        writer.start_file(".xrift/world.json", options).unwrap();
        writer.write_all(b"{}").unwrap();
        writer.finish().unwrap();

        let inspection = inspect_project_archive(archive.to_string_lossy().to_string()).unwrap();
        assert_eq!(inspection.format, "classic");
        assert_eq!(inspection.suggested_name, "classic");
        let imported = import_project_archive(
            root.to_string_lossy().to_string(),
            archive.to_string_lossy().to_string(),
            "classic-world".to_string(),
        )
        .unwrap();
        assert_eq!(imported.kind, "world");
        assert!(!root.join("classic-world/.xrift").exists());
        let _ = std::fs::remove_dir_all(&root);
    }
}
